import { useState } from "react";

export default function PortfolioAI() {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [loading, setLoading] = useState(false);
  const projectsData = `
PROJECT:
- Name: AgroMind
- Tagline: GenAI-Powered Crop Disease Detection & Remedy Platform
- Problem Statement: Farmers struggle with identifying crop diseases early and lack immediate access to expert agricultural advice.
- Tech Stack: MERN Stack (MongoDB, Express, React, Node.js), Python (Flask/FastAPI for AI), TensorFlow/Keras (CNN Models), Google Gemini API, Tailwind CSS.
- Features:
  - Real-time crop disease detection via image upload.
  - AI-generated remedies and treatment plans using Gemini.
  - Multilingual support for accessibility in rural areas.
  - Historical scan tracking for farmers.
- Architecture Summary:
  - React frontend handles image capture and UI.
  - Node.js/Express backend manages user auth and history.
  - Python microservice runs the Computer Vision model for disease classification.
  - Gemini API provides natural language explanations for the detected disease.
- Challenges Faced:
  - Bridging the data flow between Node.js backend and Python AI scripts.
  - Optimizing image processing speed for low-bandwidth rural networks.
- What I Learned:
  - Microservices architecture (connecting different backend technologies).
  - Deploying and serving Deep Learning models in a web app.
- Achievement: Built for the Smart India Hackathon (SIH) Internal Round.
- GitHub Link: https://github.com/harsh-2508/AgroMind

PROJECT:
- Name: ShikshaSaathi
- Tagline: Personalized AI Tutor & Learning Companion
- Problem Statement: Traditional education lacks personalization; students need 24/7 guidance tailored to their specific learning pace and gaps.
- Tech Stack: React.js, Node.js, Express, MongoDB, Google Gemini API, Firebase (Auth).
- Features:
  - Adaptive learning paths generated by AI based on student performance.
  - 24/7 AI Chatbot for instant doubt resolution.
  - Progress tracking and analytics dashboard.
  - Gamified learning elements to increase engagement.
- Architecture Summary:
  - React frontend provides an interactive chat interface.
  - Node.js backend manages session contexts and user data.
  - Gemini 1.5 Flash integration for high-speed, low-latency responses.
- Challenges Faced:
  - Prompt engineering to ensure the AI behaves like a supportive tutor, not just a search engine.
  - Managing context window limits during long study sessions.
- What I Learned:
  - Advanced Prompt Engineering and Context Management.
  - Building secure, scalable REST APIs for educational data.
- Achievement: Participated in 'ShikshaLokam' and 'Hack-n-Go MongoDB' hackathons.
- GitHub Link: https://github.com/harsh-2508/ShikshaSaathi

PROJECT:
- Name: VidyaDrishti
- Tagline: Rural Education Analytics Dashboard
- Problem Statement: Administrators and NGOs lack visualized data to track dropout rates, attendance, and resource allocation in rural schools.
- Tech Stack: MERN Stack (MongoDB, Express, React, Node.js), Chart.js / Recharts, Tailwind CSS.
- Features:
  - Interactive data visualization (graphs, heatmaps) of student performance.
  - School-wise and district-wise comparison tools.
  - Automated report generation for government officials.
  - Resource gap identification (e.g., identifying schools with low teacher-student ratios).
- Architecture Summary:
  - Aggregates complex datasets from MongoDB.
  - React frontend renders dynamic charts using Chart.js.
  - Optimized backend queries for fast loading of large datasets.
- Challenges Faced:
  - Handling and cleaning inconsistent data formats.
  - Designing an intuitive UI for non-technical government staff.
- What I Learned:
  - Data Visualization principles and libraries.
  - Writing complex MongoDB Aggregation Pipelines.
- GitHub Link: https://github.com/harsh-2508/VidyaDrishti
`;

  const askPortfolio = async () => {
    if (!question.trim()) return;
    setLoading(true);
    setAnswer("");

    try {
      // FIX: Added 'await' here
      const res = await fetch("http://localhost:8080/api/portfolio-abilities", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          question,
          projects: projectsData// Ensure this matches backend expectation
        }),
      });
      
      // FIX: Added 'await' here
      const data = await res.json();
      setAnswer(data.answer);
    } catch (err) {
      console.error(err);
      setAnswer("Sorry, PortfolioAI is unable to respond right now.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="h-full flex flex-col p-6 w-full">
      <h3 className="text-3xl md:text-4xl font-bold mb-3 text-white">Portfolio AI</h3>

      <p className="text-gray-400 mb-8 max-w-2xl">
        An AI assistant that answers questions about my portfolio using only
        verified project and skill data. It does not exaggerate or invent
        information.
      </p>

      {/* Input Box */}
      <div className="border border-gray-700 rounded-xl p-4 bg-black/50">
        <textarea
          className="w-full h-32 bg-transparent resize-none focus:outline-none text-white placeholder:text-gray-600"
          placeholder="Ask about my projects, skills, strengths, or areas I’m improving…"
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
        />

        <div className="flex justify-between items-center mt-3">
          <span className="text-xs text-gray-500">
            Powered by Google Gemini
          </span>

          <button
            onClick={askPortfolio}
            disabled={loading}
            className="px-5 py-2 rounded-lg bg-white text-black font-medium hover:opacity-90 disabled:opacity-50"
          >
            {loading ? "Thinking..." : "Ask Portfolio"}
          </button>
        </div>
      </div>

      {/* Answer Area - Will expand the card naturally now */}
      {answer && (
        <div className="mt-8 border border-white/10 rounded-xl p-6 bg-zinc-900/50 animate-in fade-in duration-500">
          <h3 className="font-semibold mb-3 text-violet-300">Portfolio Response:</h3>
          <div className="whitespace-pre-line text-gray-200 leading-relaxed text-base h-full">
            {answer}
          </div>
        </div>
      )}
    </div>
  );
}
